### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by ZCombs** [byronknoll/battle-map-explorer#2]
Hi,
This looks awesome and I'm interested in using the tool in a site I'm building for my group but I'm not sure as to the easiest way to get started with it. Can you uploaded this (and visibility-polygon-js) to npm? If not, what would the easiest way to implement this be?

**Comment by byronknoll** [comment]
Hi, I have never used npm before. I don't think npm would make things easier. To use this library, you just need to copy three javascript files to wherever you are hosting the webpage. The three files are: "battle-map-explorer.js", and the two files in the "external" directory. Take a look at "example-map.html" for an example. To modify/run example-map.html, just download all the files from this project to some directory on your computer. Let me know if you have any questions.
