### ISSUE TITLE
Multiple Crosshair

### ISSUE THREAD

**Issue by rDieCbw** [byronknoll/battle-map-explorer#3]
There is a possibility to use more then one crosshair? 
The general idea is, The crosshair is equivalent to a Player Token and there is more then one player on a party. 

There is a possibility to Add multiples crosshairs and, mode one at once by clicking on it? 
The crosshair should see each other but only the selected one should interact with the polygon vision. 

I'm trying to figure out this by encapsulating the battle-map-explorer inside an Vue.Js component with the array of players and changing the instance of the map by clicking on one token. (unfortunately there is no code about it yet, I'm just mind-coding it) 

If you have some contact information that we can discuss about, please send-me

**Comment by byronknoll** [comment]
This is a reasonable feature request, but I am not working on this project anymore and don't plan to add any new features. Any future development will need to be done by someone else.

**Comment by rDieCbw** [comment]
I mean, I'm probably try to develop this feature. But bro, this code sill a little complex to me.

This is a possible feature (I guess that should be the main question).

**Comment by byronknoll** [comment]
Yes, it definitely is possible to implement, but I guess the difficulty depends on your level of programming experience. I won't have time to provide support in terms of explaining the existing code or guiding how to implement this feature.

**Comment by rDieCbw** [comment]
Don't worry about that. Will figure how the code works. 
You've provide enough incentive to code!
